package compiler

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/everglowlabs/codedna/internal/schema"
)

// Compiler defines the interface for translating DNA_Schema into target formats.
type Compiler interface {
	Compile(dna schema.DNA_Schema) (map[string]string, error)
}

// CursorCompiler exports rules for Cursor / Antigravity (.cursorrules)
type CursorCompiler struct{}

func (c *CursorCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine globs from samples
		globMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				globMap["*"+ext] = true
			} else {
				globMap[dir+"/**/*"+ext] = true
			}
		}

		var globs []string
		for g := range globMap {
			globs = append(globs, g)
		}

		// YAML Frontmatter
		sb.WriteString("---\n")
		sb.WriteString(fmt.Sprintf("description: %s\n", s.Description))
		sb.WriteString("globs: ")
		if len(globs) == 0 {
			sb.WriteString("**/*")
		} else {
			sb.WriteString(strings.Join(globs, ", "))
		}
		sb.WriteString("\n")
		sb.WriteString("alwaysApply: false\n")
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		filename := sanitizeFilename(s.Title)
		fullPath := fmt.Sprintf(".cursor/rules/%s.mdc", filename)
		outputs[fullPath] = sb.String()
	}

	return outputs, nil
}

// CopilotCompiler exports rules for VS Code / GitHub Copilot
type CopilotCompiler struct{}

func (c *CopilotCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine globs from samples
		globMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				globMap["*"+ext] = true
			} else {
				globMap[dir+"/**/*"+ext] = true
			}
		}

		var globs []string
		for g := range globMap {
			globs = append(globs, g)
		}

		// YAML Frontmatter
		sb.WriteString("---\n")
		sb.WriteString("globs:\n")
		if len(globs) == 0 {
			sb.WriteString("  - \"**/*\"\n")
		} else {
			for _, g := range globs {
				sb.WriteString(fmt.Sprintf("  - \"%s\"\n", g))
			}
		}
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Rationale\n")
		sb.WriteString(s.Rationale + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		// Sanitize title for filename
		filename := strings.ToLower(s.Title)
		filename = strings.ReplaceAll(filename, " ", "_")
		filename = strings.ReplaceAll(filename, "/", "_")
		fullPath := fmt.Sprintf(".github/instructions/%s.instructions.md", filename)

		outputs[fullPath] = sb.String()
	}

	// Also add the legacy root file if there are global instructions?
	// For now, let's just stick to modularity as it's cleaner.

	return outputs, nil
}

// MarkdownCompiler exports human-readable standards
type MarkdownCompiler struct{}

func (c *MarkdownCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s: Engineering Standards\n\n", dna.ProjectName))
	sb.WriteString(fmt.Sprintf("*Generated by CodeDNA on %s*\n\n", dna.GeneratedAt.Format("2006-01-02")))

	for _, s := range dna.Standards {
		sb.WriteString(fmt.Sprintf("## %s\n", s.Title))
		sb.WriteString(fmt.Sprintf("> %s\n\n", s.Rationale))
		sb.WriteString("### Patterns Detected\n")
		for _, p := range s.Patterns {
			sb.WriteString(fmt.Sprintf("- `%s`\n", p))
		}
		sb.WriteString("\n### Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}
		sb.WriteString("\n---\n\n")
	}

	return map[string]string{
		"CODEDNA_STANDARDS.md": sb.String(),
	}, nil
}

// JSONCompiler exports the raw DNA schema
type JSONCompiler struct{}

func (c *JSONCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	data, err := json.MarshalIndent(dna, "", "  ")
	if err != nil {
		return nil, err
	}
	return map[string]string{
		"codedna.json": string(data),
	}, nil
}

// AntigravityCompiler exports modular rules for Antigravity (.agents/rules/*.md)
type AntigravityCompiler struct{}

func (c *AntigravityCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("# %s\n\n", s.Title))
		sb.WriteString(fmt.Sprintf("Category: %s\n", s.Category))
		sb.WriteString(fmt.Sprintf("Rationale: %s\n\n", s.Rationale))
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		if len(s.Samples) > 0 {
			sb.WriteString("\n## Examples\n")
			for _, sample := range s.Samples {
				sb.WriteString(fmt.Sprintf("```%s\n// File: %s\n%s\n```\n\n", sample.Language, sample.FilePath, sample.Content))
			}
		}

		// Sanitize title for filename
		filename := strings.ToLower(s.Title)
		filename = strings.ReplaceAll(filename, " ", "_")
		filename = strings.ReplaceAll(filename, "/", "_")
		fullPath := fmt.Sprintf(".agents/rules/%s.md", filename)

		content := sb.String()
		// Limit to 12,000 chars as per Antigravity docs
		if len(content) > 12000 {
			content = content[:11997] + "..."
		}

		outputs[fullPath] = content
	}

	return outputs, nil
}

// ClaudeCompiler exports rules for Claude Dev / Continue.dev (CLAUDE.md)
type ClaudeCompiler struct{}

func (c *ClaudeCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	// 1. Generate Lean CLAUDE.md
	var mainSb strings.Builder
	mainSb.WriteString("# " + dna.ProjectName + "\n\n")
	mainSb.WriteString("## Project Summary\n")
	mainSb.WriteString("Engineering standards and patterns extracted by CodeDNA.\n\n")
	mainSb.WriteString("## Standards Overview\n")
	for _, s := range dna.Standards {
		mainSb.WriteString(fmt.Sprintf("- [%s](.claude/rules/%s.md): %s\n", s.Title, sanitizeFilename(s.Title), s.Description))
	}
	outputs["CLAUDE.md"] = mainSb.String()

	// 2. Generate Modular Rules
	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine paths from samples
		pathMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				pathMap["*"+ext] = true
			} else {
				pathMap[dir+"/**/*"+ext] = true
			}
		}

		var paths []string
		for p := range pathMap {
			paths = append(paths, p)
		}

		// YAML Frontmatter (Claude uses 'paths')
		sb.WriteString("---\n")
		sb.WriteString("paths:\n")
		if len(paths) == 0 {
			sb.WriteString("  - \"**/*\"\n")
		} else {
			for _, p := range paths {
				sb.WriteString(fmt.Sprintf("  - \"%s\"\n", p))
			}
		}
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		filename := sanitizeFilename(s.Title)
		fullPath := fmt.Sprintf(".claude/rules/%s.md", filename)
		outputs[fullPath] = sb.String()
	}

	return outputs, nil
}

// Helper to sanitize filenames
func sanitizeFilename(s string) string {
	res := strings.ToLower(s)
	res = strings.ReplaceAll(res, " ", "_")
	res = strings.ReplaceAll(res, "/", "_")
	return res
}

// ContinueCompiler exports rules for Continue.dev (.continue/rules/*.md)
type ContinueCompiler struct{}

func (c *ContinueCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine globs from samples
		globMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				globMap["*"+ext] = true
			} else {
				globMap[dir+"/**/*"+ext] = true
			}
		}

		var globs []string
		for g := range globMap {
			globs = append(globs, g)
		}

		// YAML Frontmatter
		sb.WriteString("---\n")
		sb.WriteString(fmt.Sprintf("name: %s\n", s.Title))
		sb.WriteString(fmt.Sprintf("description: %s\n", s.Description))
		sb.WriteString("globs:\n")
		if len(globs) == 0 {
			sb.WriteString("  - \"**/*\"\n")
		} else {
			for _, g := range globs {
				sb.WriteString(fmt.Sprintf("  - \"%s\"\n", g))
			}
		}
		sb.WriteString("alwaysApply: false\n")
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		filename := sanitizeFilename(s.Title)
		fullPath := fmt.Sprintf(".continue/rules/%s.md", filename)
		outputs[fullPath] = sb.String()
	}

	return outputs, nil
}

// WindsurfCompiler exports rules for Windsurf Cascade (.windsurf/rules/*.md)
type WindsurfCompiler struct{}

func (c *WindsurfCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine globs from samples
		globMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				globMap["*"+ext] = true
			} else {
				globMap[dir+"/**/*"+ext] = true
			}
		}

		var globs []string
		for g := range globMap {
			globs = append(globs, g)
		}

		// YAML Frontmatter
		sb.WriteString("---\n")
		sb.WriteString("trigger: glob\n")
		sb.WriteString("globs: ")
		if len(globs) == 0 {
			sb.WriteString("**/*")
		} else {
			sb.WriteString(strings.Join(globs, ", "))
		}
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("description: %s\n", s.Description))
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		filename := sanitizeFilename(s.Title)
		fullPath := fmt.Sprintf(".windsurf/rules/%s.md", filename)
		outputs[fullPath] = sb.String()
	}

	return outputs, nil
}

// JetBrainsCompiler exports rules for JetBrains AI Assistant (.aiassistant/rules/*.md)
type JetBrainsCompiler struct{}

func (c *JetBrainsCompiler) Compile(dna schema.DNA_Schema) (map[string]string, error) {
	outputs := make(map[string]string)

	for _, s := range dna.Standards {
		var sb strings.Builder

		// Determine pattern from samples
		globMap := make(map[string]bool)
		for _, sample := range s.Samples {
			dir := filepath.Dir(sample.FilePath)
			ext := filepath.Ext(sample.FilePath)
			if dir == "." {
				globMap["*"+ext] = true
			} else {
				globMap[dir+"/**/*"+ext] = true
			}
		}

		var globs []string
		for g := range globMap {
			globs = append(globs, g)
		}

		// YAML Frontmatter
		sb.WriteString("---\n")
		sb.WriteString("type: file patterns\n")
		sb.WriteString("pattern: \"")
		if len(globs) == 0 {
			sb.WriteString("**/*")
		} else {
			sb.WriteString(strings.Join(globs, ", "))
		}
		sb.WriteString("\"\n")
		sb.WriteString("---\n\n")

		sb.WriteString("# " + s.Title + "\n\n")
		sb.WriteString(s.Description + "\n\n")
		sb.WriteString("## Guidelines\n")
		for _, rule := range s.Rules {
			sb.WriteString(fmt.Sprintf("- %s\n", rule))
		}

		filename := sanitizeFilename(s.Title)
		fullPath := fmt.Sprintf(".aiassistant/rules/%s.md", filename)
		outputs[fullPath] = sb.String()
	}

	return outputs, nil
}
